USE stats;
INSERT INTO tickets (ticket_code, name, date) VALUES
    ('AAPL', 'Apple', UNIX_TIMESTAMP()),
    ('AMD', 'Amd', UNIX_TIMESTAMP()),
    ('BRKB', 'Berkshire Hathaway', UNIX_TIMESTAMP()),
    ('DISN', 'Disney', UNIX_TIMESTAMP()),
    ('GOOGL', 'Google', UNIX_TIMESTAMP()),
    ('INTC', 'Intel', UNIX_TIMESTAMP()),
    ('JPM', 'Jpmorgan Chase & Co.', UNIX_TIMESTAMP()),
    ('KO', 'Coca cola', UNIX_TIMESTAMP()),
    ('MA', 'Mastercard', UNIX_TIMESTAMP()),
    ('MCD', 'Mac Donalds', UNIX_TIMESTAMP()),
    ('MELI', 'Mercado libre', UNIX_TIMESTAMP()),
    ('META', 'Meta', UNIX_TIMESTAMP()),
    ('MSFT', 'Microsoft', UNIX_TIMESTAMP()),
    ('NVDA', 'Nvidia', UNIX_TIMESTAMP()),
    ('PBR', 'Petrobras', UNIX_TIMESTAMP()),
    ('PEP', 'Pepsico', UNIX_TIMESTAMP()),
    ('V', 'Visa', UNIX_TIMESTAMP()),
    ('VIST', 'Vista', UNIX_TIMESTAMP()),
    ('WMT', 'Wallmart', UNIX_TIMESTAMP()),
    ('PAMP', 'Pampa', UNIX_TIMESTAMP()),
    ('YPF', 'Ypf', UNIX_TIMESTAMP()),
    ('IBIT', 'iShares Bitcoin Trust ETF', UNIX_TIMESTAMP()),
    ('SPY', 'SPDR S&P 500 ETF', UNIX_TIMESTAMP()),
    ('GGAL', 'Grupo Financiero Galicia', UNIX_TIMESTAMP()),
    ('LOMA', 'Loma Negra', UNIX_TIMESTAMP()),
    ('YPFD', 'YPF (Argentina)', UNIX_TIMESTAMP()),
    ('BYMA', 'Bolsas y Mercados Argentinos', UNIX_TIMESTAMP()),
    ('TXAR', 'Ternium Argentina', UNIX_TIMESTAMP()),
    ('TGSU2', 'Transportadora de Gas del Sur', UNIX_TIMESTAMP()),
    ('ALUA', 'Aluar', UNIX_TIMESTAMP()),
    ('COME', 'Sociedad Comercial del Plata', UNIX_TIMESTAMP()),
    ('JD', 'JD.com', UNIX_TIMESTAMP()),
    ('NTES', 'NetEase', UNIX_TIMESTAMP()),
    ('UNH', 'UnitedHealth Group', UNIX_TIMESTAMP()),
    ('TSLA', 'Tesla', UNIX_TIMESTAMP()),
    ('B', 'Barnes Group', UNIX_TIMESTAMP()),
    ('HMY', 'Harmony Gold Mining', UNIX_TIMESTAMP()),
    ('FDX', 'FedEx', UNIX_TIMESTAMP()),
    ('XOM', 'ExxonMobil', UNIX_TIMESTAMP()),
    ('WFC', 'Wells Fargo', UNIX_TIMESTAMP()),
    ('TWTR', 'Twitter', UNIX_TIMESTAMP()),
    ('AMZN', 'Amazon', UNIX_TIMESTAMP()),
    ('ZM', 'Zoom Video Communications', UNIX_TIMESTAMP()),
    ('ABEV', 'Ambev', UNIX_TIMESTAMP()),
    ('SPOT', 'Spotify', UNIX_TIMESTAMP()),
    ('PYPL', 'PayPal', UNIX_TIMESTAMP()),
    ('BA', 'Boeing', UNIX_TIMESTAMP()),
    ('QCOM', 'Qualcomm', UNIX_TIMESTAMP()),
    ('BABA', 'Alibaba', UNIX_TIMESTAMP()),
    ('AXP', 'American Express', UNIX_TIMESTAMP())
ON DUPLICATE KEY UPDATE name=VALUES(name), date=VALUES(date);
